### ISSUE TITLE
open the plugin page shows error

### ISSUE THREAD

**Issue by archonwang** [flant/redmine_issue_priorities_per_tracker#1]
when i configure it in setting. it shows an error

Started GET "/admin/issue_priorities_per_tracker" for 127.0.0.1 at Fri Jul 20 13:31:04 +0800 2012
Processing by IssuePrioritiesPerTrackerController#index as HTML
  Rendered plugins/redmine_issue_priorities_per_tracker/app/views/issue_priorities_per_tracker/index.html.erb within layouts/admin (218.8ms)
Completed 500 Internal Server Error in 484ms

ActionView::Template::Error (Mysql::Error: Table 'redmine_1_4.issue_priorities_trackers' doesn't exist: SELECT  1 AS one FROM `enumerations` INNER JOIN `issue_priorities_trackers` ON `enumerations`.`id` = `issue_priorities_trackers`.`issue_priority_id` WHERE `enumerations`.`type` IN ('IssuePriority') AND `issue_priorities_trackers`.`tracker_id` = 1 AND `enumerations`.`id` = 3 ORDER BY enumerations.position ASC LIMIT 1):
    26:     </td>
    27:     <% issue_priorities = tracker.issue_priorities -%>
    28:     <% @issue_priorities.each do |issue_priority| -%>
    29:       <% issue_priority_included = issue_priorities.include?(issue_priority) %>
    30:       <td align="center" id="<%= "relation_#{tracker.id}_#{issue_priority.id}" -%>">
    31:         <%= render "checkbox", :tracker => tracker, :issue_priority => issue_priority, :issue_priority_included => issue_priority_included %>
    32:       </td>
  activerecord (3.2.6) lib/active_record/connection_adapters/mysql_adapter.rb:346:in `prepare'
  activerecord (3.2.6) lib/active_record/connection_adapters/mysql_adapter.rb:346:in`exec_stmt'
  activerecord (3.2.6) lib/active_record/connection_adapters/mysql_adapter.rb:286:in `exec_query'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract_adapter.rb:280:in`log'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract_adapter.rb:275:in`log'
  activerecord (3.2.6) lib/active_record/connection_adapters/mysql_adapter.rb:285:in `exec_query'
  activerecord (3.2.6) lib/active_record/connection_adapters/mysql_adapter.rb:415:in`select'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/query_cache.rb:61:in`select_all'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/query_cache.rb:75:in `cache_sql'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/query_cache.rb:61:in`select_all'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_one'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/database_statements.rb:30:in`select_value'
  activerecord (3.2.6) lib/active_record/relation/finder_methods.rb:202:in `exists?'
  activerecord (3.2.6) lib/active_record/associations/collection_association.rb:324:in`include?'
  C:0:in `__send__'
  C:0:in`include?'
  plugins/redmine_issue_priorities_per_tracker/app/views/issue_priorities_per_tracker/index.html.erb:29:in `_plugins_redmine_issue_priorities_per_tracker_app_views_issue_priorities_per_tracker_index_html_erb__277636467_52252884'
  plugins/redmine_issue_priorities_per_tracker/app/views/issue_priorities_per_tracker/index.html.erb:28:in`each'
  plugins/redmine_issue_priorities_per_tracker/app/views/issue_priorities_per_tracker/index.html.erb:28:in `_plugins_redmine_issue_priorities_per_tracker_app_views_issue_priorities_per_tracker_index_html_erb__277636467_52252884'
  plugins/redmine_issue_priorities_per_tracker/app/views/issue_priorities_per_tracker/index.html.erb:22:in`each'
  plugins/redmine_issue_priorities_per_tracker/app/views/issue_priorities_per_tracker/index.html.erb:22:in `_plugins_redmine_issue_priorities_per_tracker_app_views_issue_priorities_per_tracker_index_html_erb__277636467_52252884'
  actionpack (3.2.6) lib/action_view/template.rb:145:in`send'
  actionpack (3.2.6) lib/action_view/template.rb:145:in `render'
  activesupport (3.2.6) lib/active_support/notifications.rb:125:in`instrument'
  actionpack (3.2.6) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:47:in`render_template'
  actionpack (3.2.6) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in`instrument'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.6) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:46:in`render_template'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:45:in`render_template'
  actionpack (3.2.6) lib/action_view/renderer/template_renderer.rb:18:in `render'
  actionpack (3.2.6) lib/action_view/renderer/renderer.rb:36:in`render_template'
  actionpack (3.2.6) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:110:in`_render_template'
  actionpack (3.2.6) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:103:in`render_to_body'
  actionpack (3.2.6) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.6) lib/action_controller/metal/compatibility.rb:50:in`render_to_body'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.6) lib/action_controller/metal/rendering.rb:16:in`render'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:40:in `render'
  activesupport (3.2.6) lib/active_support/core_ext/benchmark.rb:5:in`ms'
  C:/Ruby187/lib/ruby/1.8/benchmark.rb:308:in `realtime'
  activesupport (3.2.6) lib/active_support/core_ext/benchmark.rb:5:in`ms'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:40:in `render'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:83:in`cleanup_view_runtime'
  activerecord (3.2.6) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:39:in`render'
  actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:5:in`send_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/rendering.rb:10:in`process_action'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:18:in `process_action'
  activesupport (3.2.6) lib/active_support/callbacks.rb:458:in`_run__32843430__process_action__199225275__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `send'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in`send'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:17:in`process_action'
  actionpack (3.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:30:in`process_action'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.2.6) lib/action_controller/metal/params_wrapper.rb:206:in `process_action'
  activerecord (3.2.6) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:45:in`process'
  actionpack (3.2.6) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.6) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.2.6) lib/action_controller/metal.rb:246:in `action'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in`call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:36:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `call'
  journey (1.0.4) lib/journey/router.rb:56:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:600:in`call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.1) lib/rack/etag.rb:23:in `call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in`context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/cookies.rb:338:in`call'
  activerecord (3.2.6) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in`_run__397314981__call__4__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `send'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in`send'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.6) lib/rails/rack/logger.rb:26:in`call_app'
  railties (3.2.6) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.6) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.1) lib/rack/lock.rb:15:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/static.rb:62:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.6) lib/rails/engine.rb:479:in `call'
  railties (3.2.6) lib/rails/application.rb:220:in`call'
  railties (3.2.6) lib/rails/railtie/configurable.rb:30:in `send'
  railties (3.2.6) lib/rails/railtie/configurable.rb:30:in`method_missing'
  thin (1.4.1) lib/thin/connection.rb:80:in `pre_process'
  thin (1.4.1) lib/thin/connection.rb:78:in`catch'
  thin (1.4.1) lib/thin/connection.rb:78:in `pre_process'
  thin (1.4.1) lib/thin/connection.rb:53:in`process'
  thin (1.4.1) lib/thin/connection.rb:38:in `receive_data'
  eventmachine (0.12.10) lib/eventmachine.rb:256:in`run_machine'
  eventmachine (0.12.10) lib/eventmachine.rb:256:in `run'
  thin (1.4.1) lib/thin/backends/base.rb:63:in`start'
  thin (1.4.1) lib/thin/server.rb:159:in `start'
  thin (1.4.1) lib/thin/controllers/controller.rb:86:in`start'
  thin (1.4.1) lib/thin/runner.rb:185:in `send'
  thin (1.4.1) lib/thin/runner.rb:185:in`run_command'
  thin (1.4.1) lib/thin/runner.rb:151:in `run!'
  thin (1.4.1) bin/thin:6
  C:/Ruby187/bin/thin:19:in`load'
  C:/Ruby187/bin/thin:19

**Comment by kolashtov** [comment]
Thank you for your feedback.

You must run command 'rake db:migrate_plugins NAME=redmine_issue_priorities_per_tracker' in redmine directory. This command will create necessary table (issue_priorities_trackers).

**Comment by archonwang** [comment]
I will check the newest version and test it ag.

**Comment by archonwang** [comment]
I tested it on redmine 2.0 and it works well .

Thanks so  much.

I will test it on 2.1.X later.
